name: cd

on:
    push:
        branches: [main]
    
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute remote ssh command
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                script: deploy