# Generated by Django 5.1 on 2024-08-29 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratata', '0005_transaction_paid_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='ratata.transaction'),
        ),
    ]
