# Generated by Django 5.1 on 2024-09-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratata', '0006_alter_debt_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='paid_by',
        ),
    ]
