# Generated by Django 5.1 on 2024-09-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratata', '0009_accountuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='users',
        ),
    ]
